# Lesson 5 - PostgreSQL + Spring Data JPA
spring.application.name=task-management-api
server.port=8080

# --- Datasource (docker-compose ilə uyğun) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=taskuser
spring.datasource.password=taskpass
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
# update: sxem entity-lərə görə avtomatik yenilənir (yalnız development üçün!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.default-property-inclusion=non_null
logging.level.az.training.taskmanagement=INFO

# --- Lesson 6: logging ---
logging.level.root=INFO
logging.level.az.training.taskmanagement=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level [%logger{20}] - %msg%n
