# Lesson 4 - Spring Boot konfiqurasiyası
spring.application.name=task-management-api
server.port=8080

# JSON-da null sahələri gizlət (istəyə bağlı)
spring.jackson.default-property-inclusion=non_null

# Log səviyyəsi
logging.level.az.training.taskmanagement=INFO
